services:

  mlflow:
    image: python:3.13-slim
    working_dir: /mlflow

    volumes:
      - ./mlflow.db:/mlflow/mlflow.db
      - ./mlartifacts:/mlflow/mlartifacts

    command: >
     sh -c "pip install --no-cache-dir 'mlflow==3.16.0' &&
     mlflow server
     --host 0.0.0.0
     --port 5000
     --backend-store-uri sqlite:////mlflow/mlflow.db
     --artifacts-destination /mlflow/mlartifacts
     --allowed-hosts 'mlflow:5000,localhost:5000,127.0.0.1:5000'"

    ports:
      - "5000:5000"

    healthcheck:
      test: [
        "CMD",
        "python",
        '-c',
        "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 120s


  api:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000

    ports:
      - "8000:8000"

    depends_on:
      mlflow:
        condition: service_healthy


